### ISSUE TITLE
[BUG] runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BlackYuzia** [utkusen/wholeaked#7]
**OS: Windows 10**
```bash
 ./wholeaked -n secret_binary -f wholeaked.exe -t users.txt 

      ,_
    ,'  '\,_     Utku Sen's
    |_,-'_)         wholeaked
    /##c '\  (
   ' |'  -{.  )  "When you have eliminated the impossible,
     /\__-' \[]  whatever remains, however improbable,
    /'-_'\       must be the truth" - Sherlock Holmes
    '     \

Operation started
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x9ed2b5]

goroutine 1 [running]:
github.com/barasher/go-exiftool.(*Exiftool).Close(0x0)
        /Users/temporaryadmin/go/pkg/mod/github.com/barasher/go-exiftool@v1.7.0/exiftool.go:93 +0x55
panic({0xb9c3e0, 0x1189640})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/barasher/go-exiftool.(*Exiftool).ExtractMetadata(0x0, {0xc00019f678, 0x1, 0x5a})
        /Users/temporaryadmin/go/pkg/mod/github.com/barasher/go-exiftool@v1.7.0/exiftool.go:139 +0x74
main.addMetadataSignature({0xc00002c120, 0x55}, {0xc00001a79a, 0x33})
        /Users/temporaryadmin/Desktop/dev/wholeaked/main.go:336 +0x609
main.applySignature({0xc00002c120, 0x55}, {0xc00001a79a, 0x33}, 0x1, 0xf9, 0xc0)
        /Users/temporaryadmin/Desktop/dev/wholeaked/main.go:242 +0xe5
main.createLocalFiles({0xc000024110, 0xd}, {0xc0000240d0, 0xd}, 0x1, 0x0, 0x0)
        /Users/temporaryadmin/Desktop/dev/wholeaked/main.go:564 +0x4f8
main.startProcess({0xc000024110, 0xd}, {0xc000024140, 0x9}, {0xc0000240d0, 0xd}, 0x8, 0x1, 0xaa, 0x0, ...)
        /Users/temporaryadmin/Desktop/dev/wholeaked/main.go:126 +0x5eb
main.main()
        /Users/temporaryadmin/Desktop/dev/wholeaked/main.go:81 +0x4ff
```
      // users.txt
      kruzya,kruzya@kruzya.ua
      yuzia,yuzia@yuzia.ua

**Comment by cullero** [comment]
bit late, but if you've downloaded the exiftool binary, after extacting, rename it to remove the "(-k)"
